export interface Codes {
  en: string
  fr: string
  it: string
  de: string
  aa: string
  ab: string
  af: string
  am: string
  ar: string
  as: string
  ay: string
  az: string
  ba: string
  be: string
  bg: string
  bh: string
  bi: string
  bn: string
  bo: string
  br: string
  ca: string
  co: string
  cs: string
  cy: string
  da: string
  dz: string
  el: string
  eo: string
  es: string
  et: string
  eu: string
  fa: string
  fi: string
  fj: string
  fo: string
  fy: string
  ga: string
  gd: string
  gl: string
  gn: string
  gu: string
  ha: string
  hi: string
  he: string
  hr: string
  hu: string
  hy: string
  ia: string
  id: string
  ie: string
  ik: string
  in: string
  is: string
  iu: string
  iw: string
  ja: string
  ji: string
  jw: string
  ka: string
  kk: string
  kl: string
  km: string
  kn: string
  ko: string
  ks: string
  ku: string
  ky: string
  la: string
  ln: string
  lo: string
  lt: string
  lv: string
  mg: string
  mi: string
  mk: string
  ml: string
  mn: string
  mo: string
  mr: string
  ms: string
  mt: string
  my: string
  na: string
  ne: string
  nl: string
  no: string
  oc: string
  om: string
  or: string
  pa: string
  pl: string
  ps: string
  pt: string
  qu: string
  rm: string
  rn: string
  ro: string
  ru: string
  rw: string
  sa: string
  sd: string
  sg: string
  sh: string
  si: string
  sk: string
  sl: string
  sm: string
  sn: string
  so: string
  sq: string
  sr: string
  ss: string
  st: string
  su: string
  sv: string
  sw: string
  ta: string
  te: string
  tg: string
  th: string
  ti: string
  tk: string
  tl: string
  tn: string
  to: string
  tr: string
  ts: string
  tt: string
  tw: string
  ug: string
  uk: string
  ur: string
  uz: string
  vi: string
  vo: string
  wo: string
  xh: string
  yi: string
  yo: string
  za: string
  zh: string
  zu: string
  [key: string]: string
}

/* tslint:disable */
export type Types = 'en' | 'fr' | 'it' | 'de' | 'aa' | 'ab' | 'af' | 'am' | 'ar' | 'as' | 'ay' | 'az' | 'ba' | 'be' | 'bg' | 'bh' | 'bi' | 'bn' | 'bo' | 'br' | 'ca' | 'co' | 'cs' | 'cy' | 'da' | 'dz' | 'el' | 'eo' | 'es' | 'et' | 'eu' | 'fa' | 'fi' | 'fj' | 'fo' | 'fy' | 'ga' | 'gd' | 'gl' | 'gn' | 'gu' | 'ha' | 'hi' | 'he' | 'hr' | 'hu' | 'hy' | 'ia' | 'id' | 'ie' | 'ik' | 'in' | 'is' | 'iu' | 'iw' | 'ja' | 'ji' | 'jw' | 'ka' | 'kk' | 'kl' | 'km' | 'kn' | 'ko' | 'ks' | 'ku' | 'ky' | 'la' | 'ln' | 'lo' | 'lt' | 'lv' | 'mg' | 'mi' | 'mk' | 'ml' | 'mn' | 'mo' | 'mr' | 'ms' | 'mt' | 'my' | 'na' | 'ne' | 'nl' | 'no' | 'oc' | 'om' | 'or' | 'pa' | 'pl' | 'ps' | 'pt' | 'qu' | 'rm' | 'rn' | 'ro' | 'ru' | 'rw' | 'sa' | 'sd' | 'sg' | 'sh' | 'si' | 'sk' | 'sl' | 'sm' | 'sn' | 'so' | 'sq' | 'sr' | 'ss' | 'st' | 'su' | 'sv' | 'sw' | 'ta' | 'te' | 'tg' | 'th' | 'ti' | 'tk' | 'tl' | 'tn' | 'to' | 'tr' | 'ts' | 'tt' | 'tw' | 'ug' | 'uk' | 'ur' | 'uz' | 'vi' | 'vo' | 'wo' | 'xh' | 'yi' | 'yo' | 'za' | 'zh' | 'zu'
/* tslint:enable */

export const codes: Codes = {
  en: 'en',
  fr: 'fr',
  it: 'it',
  de: 'de',
  aa: 'aa',
  ab: 'ab',
  af: 'af',
  am: 'am',
  ar: 'ar',
  as: 'as',
  ay: 'ay',
  az: 'az',
  ba: 'ba',
  be: 'be',
  bg: 'bg',
  bh: 'bh',
  bi: 'bi',
  bn: 'bn',
  bo: 'bo',
  br: 'br',
  ca: 'ca',
  co: 'co',
  cs: 'cs',
  cy: 'cy',
  da: 'da',
  dz: 'dz',
  el: 'el',
  eo: 'eo',
  es: 'es',
  et: 'et',
  eu: 'eu',
  fa: 'fa',
  fi: 'fi',
  fj: 'fj',
  fo: 'fo',
  fy: 'fy',
  ga: 'ga',
  gd: 'gd',
  gl: 'gl',
  gn: 'gn',
  gu: 'gu',
  ha: 'ha',
  hi: 'hi',
  he: 'he',
  hr: 'hr',
  hu: 'hu',
  hy: 'hy',
  ia: 'ia',
  id: 'id',
  ie: 'ie',
  ik: 'ik',
  in: 'in',
  is: 'is',
  iu: 'iu',
  iw: 'iw',
  ja: 'ja',
  ji: 'ji',
  jw: 'jw',
  ka: 'ka',
  kk: 'kk',
  kl: 'kl',
  km: 'km',
  kn: 'kn',
  ko: 'ko',
  ks: 'ks',
  ku: 'ku',
  ky: 'ky',
  la: 'la',
  ln: 'ln',
  lo: 'lo',
  lt: 'lt',
  lv: 'lv',
  mg: 'mg',
  mi: 'mi',
  mk: 'mk',
  ml: 'ml',
  mn: 'mn',
  mo: 'mo',
  mr: 'mr',
  ms: 'ms',
  mt: 'mt',
  my: 'my',
  na: 'na',
  ne: 'ne',
  nl: 'nl',
  no: 'no',
  oc: 'oc',
  om: 'om',
  or: 'or',
  pa: 'pa',
  pl: 'pl',
  ps: 'ps',
  pt: 'pt',
  qu: 'qu',
  rm: 'rm',
  rn: 'rn',
  ro: 'ro',
  ru: 'ru',
  rw: 'rw',
  sa: 'sa',
  sd: 'sd',
  sg: 'sg',
  sh: 'sh',
  si: 'si',
  sk: 'sk',
  sl: 'sl',
  sm: 'sm',
  sn: 'sn',
  so: 'so',
  sq: 'sq',
  sr: 'sr',
  ss: 'ss',
  st: 'st',
  su: 'su',
  sv: 'sv',
  sw: 'sw',
  ta: 'ta',
  te: 'te',
  tg: 'tg',
  th: 'th',
  ti: 'ti',
  tk: 'tk',
  tl: 'tl',
  tn: 'tn',
  to: 'to',
  tr: 'tr',
  ts: 'ts',
  tt: 'tt',
  tw: 'tw',
  ug: 'ug',
  uk: 'uk',
  ur: 'ur',
  uz: 'uz',
  vi: 'vi',
  vo: 'vo',
  wo: 'wo',
  xh: 'xh',
  yi: 'yi',
  yo: 'yo',
  za: 'za',
  zh: 'zh',
  zu: 'zu',
}
export default {codes}
